### ISSUE TITLE
unable to update Firesbase due to GeoFirestore/GeoFire dependecies

### ISSUE THREAD

**Issue by CollinEsmon** [imperiumlabs/GeoFirestore#4]
I want to update Firebase, so I updated the GeoFirestore podspec dependency to 'Firebase', '~> 6.1.0'. However, Geofirestore has a Geofire dependancy which has a Firebase/Database (~>5.0) dependency. What can I do to update Firesbase with these dependencies?

**Comment by nedbash** [comment]
This is the same issue, and it is solved: https://github.com/imperiumlabs/GeoFirestore-iOS/issues/18
